import {
  foodIcon,
  transportationIcon,
  culturalIcon,
  dailyNecessityIcon,
  clothesIcon,
  beautyIcon,
  medicalHealthIcon,
  educationIcon,
  communicationIcon,
  gatheringIcon,
  eventsIcon,
  savingIcon,
  electronicsIcon,
  utilitiesIcon,
  cardIcon,
  etcIcon,
  salaryIcon,
  moneyIcon,
  cashIcon,
  debitCardIcon,
  creditCardIcon,
} from '@/lib/utils/Icons';

const tags = [
  { label: '식비', icon: foodIcon },
  { label: '문화생활', icon: culturalIcon },
  { label: '교통비', icon: transportationIcon },
  { label: '생필품', icon: dailyNecessityIcon },
  { label: '의류', icon: clothesIcon },
  { label: '미용', icon: beautyIcon },
  { label: '의료/건강', icon: medicalHealthIcon },
  { label: '교육', icon: educationIcon },
  { label: '통신비', icon: communicationIcon },
  { label: '회식/모임', icon: gatheringIcon },
  { label: '경조사', icon: eventsIcon },
  { label: '저축', icon: savingIcon },
  { label: '가전', icon: electronicsIcon },
  { label: '공과금', icon: utilitiesIcon },
  { label: '카드대금', icon: cardIcon },
  { label: '기타', icon: etcIcon },
  { label: '월급', icon: salaryIcon },
  { label: '용돈', icon: moneyIcon },
  { label: '현금', icon: cashIcon },
  { label: '체크카드', icon: debitCardIcon },
  { label: '신용카드', icon: creditCardIcon },
];

export default tags;
